modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Right"

[[mods]]
modId = "stacked_trims"
version = "${version}"
displayName = "Stacked Trims"
authors = "Flechazo"
description = '''
The high version port of Netherite Plus Mod
Add more netherite items into game.
'''
logoFile = "icon.png"

[[dependencies.stacked_trims]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stacked_trims]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stacked_trims]]
modId = "architectury"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config="stacked_trims.mixins.json"

[[mixins]]
config="stacked_trims-neoforge.mixins.json"